name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  nginx:
    profiles: [ nginx ]
    extends:
      service: nginx
      # TODO mv into nginx
      file: docker-compose.${DIST_VERSION:-debian}.yml
    build:
      context: nginx
      args:
        VERSION: ${NGINX_VERSION:-stable}
    restart: unless-stopped
    network_mode: host
    ulimits:
      nproc: 127607
      nofile:
        soft: 524288
        hard: 524288
    volumes:
      # configs
      - ./nginx/crontabs:/var/spool/cron/crontabs
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/enable-php-56.conf:/etc/nginx/enable-php-56.conf:ro
      - ./nginx/enable-php-72.conf:/etc/nginx/enable-php-72.conf:ro
      - ./nginx/enable-php-74.conf:/etc/nginx/enable-php-74.conf:ro
      - ./nginx/enable-php-80.conf:/etc/nginx/enable-php-80.conf:ro
      - ./nginx/enable-php-81.conf:/etc/nginx/enable-php-81.conf:ro
      - ./nginx/enable-php-82.conf:/etc/nginx/enable-php-82.conf:ro
      - ./nginx/enable-php-83.conf:/etc/nginx/enable-php-83.conf:ro
      - ./nginx/enable-php-84.conf:/etc/nginx/enable-php-84.conf:ro
      - ./nginx/enable-php-85.conf:/etc/nginx/enable-php-85.conf:ro
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/path-security.conf:/etc/nginx/path-security.conf:ro
      - ./nginx/pathinfo.conf:/etc/nginx/pathinfo.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./nginx/wordpress.conf:/etc/nginx/wordpress.conf:ro
      # ssl
      - ./nginx/cert:/etc/nginx/cert:ro,z
      - ./nginx/ssl-cert-snakeoil.key:/etc/nginx/ssl-cert-snakeoil.key:ro
      - ./nginx/ssl-cert-snakeoil.pem:/etc/nginx/ssl-cert-snakeoil.pem:ro
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
      # log
      - ./nginx/log:/var/log/nginx:rw,z
      # data
      - ./wwwroot:/wwwroot:ro,z
      # 共享run
      - ./run:/var/run:rw,z
    environment:
      TZ: ${TZ:-UTC}
  nginx-crond:
    profiles: [ nginx ]
    extends:
      service: nginx
    command: busybox crond -f -l 8
  acme-sh:
    profiles: [ acme ]
    image: ${DOCKER_REGISTRY:-docker.io}/neilpang/acme.sh
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./acme.sh:/acme.sh:rw,z
      - ./nginx/cert:/acme.sh.d:rw,z
      - /var/run/docker.sock:/var/run/docker.sock
    command: daemon
    environment:
      TZ: ${TZ:-UTC}
  mysql80:
    profiles: [ mysql80, mysql ]
    extends:
      file: mysql/80/docker-compose.yml
      service: mysql80
  mariadb:
    profiles: [ mariadb ]
    extends:
      file: mariadb/docker-compose.yml
      service: mariadb
  redis8:
    profiles: [ redis8, redis ]
    extends:
      file: redis/8/docker-compose.yml
      service: redis8
  php56:
    profiles: [ php56 ]
    extends:
      file: php/56/docker-compose.yml
      service: php56
  php56-crond:
    profiles: [ php56 ]
    extends:
      file: php/56/docker-compose.yml
      service: php56-crond
  php72:
    profiles: [ php72 ]
    extends:
      file: php/72/docker-compose.yml
      service: php72
  php72-crond:
    profiles: [ php72 ]
    extends:
      file: php/72/docker-compose.yml
      service: php72-crond
  php74:
    profiles: [ php74 ]
    extends:
      file: php/74/docker-compose.yml
      service: php74
  php74-crond:
    profiles: [ php74, php7 ]
    extends:
      file: php/74/docker-compose.yml
      service: php74-crond
  php80:
    profiles: [ php80 ]
    extends:
      file: php/80/docker-compose.yml
      service: php80
  php80-crond:
    profiles: [ php80 ]
    extends:
      file: php/80/docker-compose.yml
      service: php80-crond
  php81:
    profiles: [ php81 ]
    extends:
      file: php/81/docker-compose.yml
      service: php81
  php81-crond:
    profiles: [ php81 ]
    extends:
      file: php/81/docker-compose.yml
      service: php81-crond
  php82:
    profiles: [ php82 ]
    extends:
      file: php/82/docker-compose.yml
      service: php82
  php82-crond:
    profiles: [ php82 ]
    extends:
      file: php/82/docker-compose.yml
      service: php82-crond
  php83:
    profiles: [ php83 ]
    extends:
      file: php/83/docker-compose.yml
      service: php83
  php83-crond:
    profiles: [ php83 ]
    extends:
      file: php/83/docker-compose.yml
      service: php83-crond
  php84:
    profiles: [ php84 ]
    extends:
      file: php/84/docker-compose.yml
      service: php84
  php84-crond:
    profiles: [ php84 ]
    extends:
      file: php/84/docker-compose.yml
      service: php84-crond
  php85:
    profiles: [ php85, php8, php ]
    extends:
      file: php/85/docker-compose.yml
      service: php85
  php85-crond:
    profiles: [ php85, php8, php ]
    extends:
      file: php/85/docker-compose.yml
      service: php85-crond
  openlitespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION:-1.9.0}-${PHP_VERSION:-lsphp85}
    env_file:
      - .env
    volumes:
      - ./ols/lsws/conf:/usr/local/lsws/conf
      - ./ols/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./ols/bin/container:/usr/local/bin
      - ./ols/sites:/var/www/vhosts/
      - ./ols/acme:/root/.acme.sh/
      - ./ols/logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 7080:7080
    network_mode: host
    restart: always
    environment:
      TZ: ${TZ:-UTC}
