name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  redis8:
    extends:
      service: redis8
      file: docker-compose.${DIST_VERSION:-debian}.yml
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data:rw,z
      - ./conf.d:/usr/local/etc/redis:ro,z
      - ./logs:/var/log/redis:rw,z
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ:-Asia/Shanghai}