name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  php85:
    extends:
      service: php85
      file: docker-compose.${DIST_VERSION:-debian}.yml
    build:
      context: .
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ../../run:/var/run:rw,z
      - ../../wwwroot:/wwwroot:rw,z
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./crond:/etc/crontabs:ro
    network_mode: host
  php85-crond:
    extends:
      service: php85
    # debian: cron, alpine: crond
    command: cron -f -l 8 || crond -f -l 8
