name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  php85:
    extends:
      service: php85
      file: docker-compose.${DIST_VERSION:-debian}.yml
    build:
      context: .
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ../../run:/var/run:rw,z
      - ../../wwwroot:/wwwroot:rw,z
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./crontabs:/var/spool/cron/crontabs:ro
    network_mode: host
    environment:
      TZ: ${TZ:-UTC}
  php85-crond:
    extends:
      service: php85
    command: busybox crond -f -l 8
