name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  php81:
    extends:
      service: php81
      file: docker-compose.${DIST_VERSION:-debian}.yml
    build:
      context: .
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ../../run:/var/run:rw,z
      - ../../wwwroot:/wwwroot:rw,z
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./crontabs:/var/spool/cron/crontabs
    network_mode: host
  php81-crond:
    extends:
      service: php81
    command: busybox crond -f -l 8
