name: ${DOCKER_COMPOSE_NAMESPACE:-dnmp}
services:
  redis:
    image: ${DOCKER_REGISTRY:-docker.io}/redis:7-${DIST_VERSION:-alpine}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data:rw,z
      - ./conf.d:/usr/local/etc/redis:ro,z
      - ./logs:/var/log/redis:rw,z
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ:-Asia/Shanghai}